### ISSUE TITLE
transition source state wildcard override

### ISSUE THREAD

**Issue by bedge** [pytransitions/transitions#227]
If I have a transition defined as:
```
machine.add_transition('to_liquid', '*', 'liquid')
```
and I want to add an exception to this, IOW, handle one source state differently.

Can I use:
```
machine.add_transition('to_liquid', '*', 'liquid')
machine.add_transition('to_liquid', 'gas', 'abort)
```
IOW, does the second line override the '*' for the one case of `to_liquid` happening in state `gas`?

**Comment by aleneum** [comment]
Hi @bedge,

transitions will be evaluated in the order they were added to the machine. `*` will actually be replaced by each state in the machine:

```python
m = Machine(states=['A', 'B', 'C'])
m. add_transition('go', '*', 'B')
# this will execute 
# m. add_transition('go', 'A', 'B')
# m. add_transition('go', 'B', 'B')
# m. add_transition('go', 'C', 'B')
```

To use your wildcard transition as fallback/generalized transition, you need to add it last.

 ```python
machine.add_transition('to_liquid', 'gas', 'abort')
machine.add_transition('to_liquid', '*', 'liquid')
```

The wildcard transition will then add a transition to the evaluation queue of state `gas` which cannot be executed though since there is no way your `['to_liquid', 'gas', 'abort']` transition will fail.

**Comment by bedge** [comment]
Perfect, exactly what I needed to know. I didn't see this order of precedence in the docs, might be worth adding.
Understood on the naming issue, thanks for pointing that out. This it not my naming scheme, I copied it from the docs for simplicity, but the point you make and the note are appreciated.
