### ISSUE TITLE
How to run a fsm forever?

### ISSUE THREAD

**Issue by 600lyy** [pytransitions/transitions#241]
Hi all,
This is a very useful tool to help create a state machine very quickly. But here I've got a very simple ( or stupid) question, that how to run a fsm forever? Bascically what I want is a fsm model which can stay "idle" when there is  no more event to trigger.

For examplel, in example.py:

**state = [ 'A', B', 'C']
transtion = [ A->B->C]

if __name__ == '__main__': 
      machine = Machine(state, transition, initial='A')**
      print(machine.state)

If I to run this machine in a python program, it will go into state 'A', print the current state, and the program will then exit immediately. So my question is how can I keep it running forever when there is nothing to trigger a transition?  Shall I implement a loop or is there any other way to do so?

Thanks
BR//Andy

**Comment by aleneum** [comment]
Hi @600lyy,

great to hear that transitions supports your development. Please refer to Stackoverflow first when it comes to usage questions. This has several advantages:

* Your question gains higher visibility since most developers look for help there
* The targeted community is larger; Some people will even help you to formulate a good question
* People get 'rewarded' with 'reputation' to help you. You also gain reputation in case this questions pops up more frequently. It's a win-win situation. 

I will close the issue now. If no one at SO can help you and/or a feature request emerges out of your question. Feel free to open another issue here and preferably reference your SO question.

Best regards!
