### ISSUE TITLE
Is there an easy way to share state machine object between two processes

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [pytransitions/transitions#249]
I have a thrift forking server in which all the requests are handled in a newly forked process. I will have to check the state of an object in every request (For. I will need to throw an exception when start request is received while the current state is in_progress). Essentially I need a shared object with state machine. As far as I understand, LockedMachine is only when there are multiple threads but not for multiple processes.

**Comment by tyarkoni** [comment]
This is more appropriate for Stack Overflow, so please post it there with the tags [python] and [transitions]. Thanks!

**Comment by aleneum** [comment]
Hello @nareshsankapellyfkrt,

`LockedMachine` uses standard locks for context management but you can pass custom context managers in case this is required. If you already figured out how to share the object between multiple processes and you just need a shareable context, you can pass a managed lock for instance:
```python
manager = multiprocessing.Manager()
machine = LockedMachine(..., machine_context=manager.Lock())
```
Just make sure the passed context is actually a context and can be passed to processes. Keep in mind that some lock mechanisms are not pickable which renders them not usable in multiprocessing queues for instance.

Sharing complex objects is not that trivial as far as I understand, so you might also consider using a remote manager for this. The example below uses a manager to maintain the `Model` instance which also contains the state machine. As you see, I does not even need a custom lock as all model operations seem to be executed in the manager's context:

```python
from multiprocessing import Process, Queue, managers
from transitions.extensions.locking import LockedMachine
import time


# executor function
def worker(model, out_queue, op):
    while True:
        try:
            # call the operation; either 'tick' or 'tock'
            getattr(model, op)()
            # after that, put message for printing
            out_queue.put(op)
        except Exception as e:
            out_queue.put(e)
            time.sleep(3)


class Model(object):

    def __init__(self):
        self.machine = LockedMachine(model=self, states=states, transitions=transitions,
                                     initial='tocked')

    # it takes a bit longer to process ticks...
    def on_enter_ticked(self):
        time.sleep(2)

    # ... than to process tocks
    def on_enter_tocked(self):
        time.sleep(1)


class StateManager(managers.BaseManager):
    pass

# register our class to be maintained by the manager
StateManager.register("Model", Model)

states = ['ticked', 'tocked']
transitions = [['tick', 'tocked', 'ticked'],
               ['tock', 'ticked', 'tocked']]

manager = StateManager()
# start manager
manager.start()
out_queue = Queue()
# create shared model
model = manager.Model()
# pass
p1 = Process(target=worker, args=(model, out_queue, 'tick'))
p2 = Process(target=worker, args=(model, out_queue, 'tock'))

p1.start()
# wait for 'tick' to be processed
time.sleep(0.2)
p2.start()
while True:
    while not out_queue.empty():
        print("Response: ", out_queue.get())

# >>> Response:  tick
# >>> Response:  tock
# >>> Response:  tick
# >>> Response:  tock
# ...
```

You can try to use `Machine` instead of  `LockedMachine` to validate that the access is actually threaded/parallel. When using `Machine`, you will encounter errors sooner or later because of wrong states.

I will close this for now since this does not look like an issue to me but like a request for recommendations. Feel free to follow up on this **in case you think it is an actual bug or missing feature** and I will open the issue again. If you need more advices for your project, consider using stackoverflow instead.

**Comment by nareshsankapellyfkrt** [comment]
Thanks.

**Comment by bedge** [comment]
I'm also looking into a better way to share a set of env data between handlers which may or may not be in the same thread.
In my current attempt I'm creating a context that wraps my shared env data class that I pass into the LockedMachine with machine_context arg. 
Then I added a self.env() to extract it from self.machine_context[0] (this bit seems a bit clunky, maybe there's a better way) The docs don't mention that this is where it's stashed, had to dig around a bit.

```
def get_event_cfg():
    global cfg_data
    if cfg_data is None:
        logger.debug('read cfg....')
        cfg = get_config('blargh')

# wrap above in context:
class EnvContext():
    def __init__(self):
        self.env = get_event_cfg()

    def __enter__(self):
        return self.env

    def __exit__(self, *args):
        pass

# Shortcut to env extraction:

from transitions.extensions import LockedMachine as Machine

class XxxxCluster(Machine):

    def env(self):
        return self.machine_context[0].env       # found it here, maybe better option?

    def __init__(self):
        env = EnvContext()
        Machine.__init__(self,
                         states=states, transitions=transitions,
                         finalize_event='finalize',
                         send_event=True,
                         queued=True,
                         machine_context=[env],
                         initial='idle')


# Using it, which works in same and other threads, timeout handlers etc:

    def finalize(self, event):
        env = self.env()
```

**Comment by aleneum** [comment]
> The docs don't mention that this is where it's stashed, had to dig around a bit.

Is there a specific advantage to retrieve it from the machine directly? Pulling a context manager from the internals of `LockedMachine` does not look beneficial to me. The intended use case is to *share* a context manager with the machine in case you need it:

```python
class XxxxCluster(Machine):

    def __init__(self):
        self.env = EnvContext()
        Machine.__init__(self,
                         states=states, transitions=transitions,
                         finalize_event='finalize',
                         send_event=True,
                         queued=True,
                         machine_context=self.env,
                         initial='idle')

    def finalize(self, event):
        pass
        # working with self.env
```

`LockedMachine` will not create a custom/own context manager in case `machine_context` is not None.

**Comment by bedge** [comment]
The reason I'm "pulling it from the internals of the Machine is not to worth "with" it (as in within it's context), but for the additional data payload it contains.

I'm probably contorting the context support for something it's not intended for. I picked up on the prior comment:
   "Sharing complex objects is not that trivial as far as I understand"
and felt that I had solved that aspect of it using this mechanism.

I don't actually need the lock aspect of the context manager, I'm using it solely to expose shared data to all handlers/callbacks. It doesn't need exclusive access. It's just a way to make a class of config data available to all of the handlers and callbacks used by the Machine, locked or otherwise, to share config data.

That said, is this negating the lock in the LockedMachine? IOW, is my "data only context" now being relied upon for synchronization, which it is not doing?

Is there a better way to expose data to multiple threads of the Machine?

**Comment by bedge** [comment]
OK, not sure what I was smoking at the time, but I'm not having the un-init model data in threads as I did earlier. 
Maybe consider nuking from my comment on down as it does nothing but confuse and overcomplicate the issue.

**Comment by aleneum** [comment]
> I'm probably contorting the context support for something it's not intended for

Well it's definitely a new way of using it. This does not have to be bad at all. Not sure its suitable for sharing resources in several processes though. 

> ie: ensure that all threads had access to the same config/env data.

I am not sure if a context manager is shared between several processes. My guess would be it is not. The *managers* I was talking about earlier are *remote* managers provided by `multiprocessing`.
For sharing resources, I'd stick to the general best practises for `multiprocessing` and Python. This usually involves shared queues and/or (remote) managers.

Note this is only relevant for `multiprocessing` not threading in general. In case of threading you can use `LockedMachine` and access model resources in callbacks (and this access will also be synchronised aka locked). This just start to get more complicated if you need multiple *processes* to make use of multiple CPU cores.

> That said, is this negating the lock in the LockedMachine? IOW, is my "data only context" now being relied upon for synchronization, which it is not doing?

yes, the initial use case was that a user already has a lock for synchronising resource access and wants to reduce the locking overhead by sharing the very same lock with the machine. But context managers can do much more of course.

But initial use cases can and should be extended wherever necessary. This being said I think this kind of issues should be stated on Stackoverflow to increase visibility (of the issue and also transitions). If a feature request or a bug emerges while trying to solve a task, feel free to open an issue for it. If you tag your question with `transitions` and `python`, a Stackoverflow question will also pop up in our newsfeeds.
