### ISSUE TITLE
Python 3.6 support for GraphMachines

### ISSUE THREAD

**Issue by e-d-n-a** [pytransitions/transitions#255]
It seems [pygraphviz](https://pypi.python.org/pypi/pygraphviz/1.4rc1) isn't yet compatible with Python 3.6!?
On it's [homepage](http://pygraphviz.github.io/) you can see, that version 1.5 is in development and on [Github](https://github.com/pygraphviz/pygraphviz/commit/ecbc387ebb54eb35333a5f605765d83b5cff9ab1) it seems to approach compatibility with 3.6.

To be honest, I haven't looked much into it, but it seems it could take a while until this will be available.

Would you consider adding support for 3.6 by using another graphviz-wrapper like [graphviz](https://pypi.python.org/pypi/graphviz/0.8), which already has support up to 3.6!?

Maybe I'm wrong here and there is already a way to make the diagrams-feature work, but I got a compilation error with version 1.3.1 of pygraphviz, that gets installed when using pip like this:
`pip install transitions[diagrams]`

I'm not keen to modify the transitions module or pygraphviz myself to make this work.
I'd rather use another library instead for visualizing a generated graph of the machine.

EDIT:
I'm not quite sure, but at the moment it seems NetworkX also does NOT support Python 3 for drawing!?
According to [this](http://networkx.readthedocs.io/en/stable/tutorial/tutorial.html#drawing-graphs) and by using [various libraries](http://networkx.readthedocs.io/en/stable/reference/drawing.html).

I hope you can help to come up with an easy solution for the Python 3.6 environment.
Thanks!

**Comment by aleneum** [comment]
Hello @e-d-n-a,

> It seems pygraphviz isn't yet compatible with Python 3.6!?

The ubuntu-based [travis-built](https://travis-ci.org/pytransitions/transitions/jobs/271806480) works just fine. I personally test `transitions` with `tox` on macOS Sierra and it also works with `pygraphviz`.

> Would you consider adding support for 3.6 by using another graphviz-wrapper like graphviz, which already has support up to 3.6!?

graphviz does not offer all required features as far as I remember. We alter nodes and attributes of the graph quite a lot and also query the graph at some points to retrieve edges. We do not plan to support another graphviz module in the foreseeable future but we will of course review a pull request in case someone is willing to give it a shot.

> Maybe I'm wrong here and there is already a way to make the diagrams-feature work, but I got a compilation error with version 1.3.1 of pygraphviz, that gets installed when using pip like this:
pip install transitions[diagrams]

You could try to install pygraphviz manually with `pip install pygraphviz` or find another way. Maybe clone the repo and build `pygraphviz` from source or -- if you use *nix -- install the pygraphviz (homebrew) package instead of the pip version. 

> I'm not quite sure, but at the moment it seems NetworkX also does NOT support Python 3 for drawing!?

I just have limited experience with NetworkX but yes, the current stable documentation mentions that drawings are not support for Python 3.0 and above.

**Comment by e-d-n-a** [comment]
There are people talking about this issue in various PyGraphviz-Issues on Github (eg [here](https://github.com/pygraphviz/pygraphviz/issues/16) and [here](https://github.com/pygraphviz/pygraphviz/issues/74)).
And there is a [Patch](https://github.com/Kagami/pygraphviz/commit/fe442dc16accb629c3feaf157af75f67ccabbd6e) you have to use to make it compile.

From that you might be able to get PyGraphviz to work under Windows and Python 3.6, but I couldn't figure out a solution yet. For Python 3.4 it seems to be easy, as there is a compiled [package](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygraphviz) from C. Gohlke's archive, which includes statically linked libraries, which circumvents the main problems you can have with compiling and linking. But normally you get an install, that fails tests or crashes when being used.

Maybe this describes how you can use this wheel in a Python 3.6 environment, but I'm not sure.
I'm working with WinPython-32bit-3.6.1.0Qt5 at the moment and do not know how to adapt this.

So I'll probably go with a seperate Python 3.4 environment to at least get something running or even switch to a linux install, if nescessary.

**Comment by aleneum** [comment]
I will close this issue since it seems to be a `pygraphviz` issue we cannot help with. If you consider this to be a `transitions` issue as well, please give some feedback and I will open up this issue again.
