### ISSUE TITLE
Warning: Model already has a 'to'-method. It will NOT be overwritten by NestedMachine

### ISSUE THREAD

**Issue by lromor** [pytransitions/transitions#265]
Hello, 
this warning is a bit annoying, what is its purpose for the enduser/what the enduser can do to remove it?

thank you,

-l

**Comment by aleneum** [comment]
> this warning is a bit annoying, what is its purpose for the enduser

`transitions` adds some convenience functions to your model such as `is_<state_name>` or `to_<state_name>`. `HierarchicalMachine` also adds a `to` function to your model which you can use to transit to (nested) states directly (e.g. `model.to('stateA.substateA1.subsubstateA1a')`).
In case your model already has a function/property called `to`, this warning is emitted and the current `to`-attribute is kept.
So if you have not added a model function called `to`, I assume you are using the `HierarchicalMachine` instance as a model. `HierarchicalMachine` has a function called `to`.

> what the enduser can do to remove it?

1. use a dedicated model instead of `HierarchicalMachine` (in case you are using it that way currently)
2. Rename your model function `to` (in case you already use a dedicated model)
3. ```python
    import logging
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger('transitions.extensions.nested').setLevel(level=logging.ERROR)
    ```
`3` will also silence warnings about invalid triggers in nested states though.

It might be a good idea to rename this function to `to_state` to get rid of this naming collision.
After all, default values should not cause warnings.

**Comment by aleneum** [comment]
Update: I will rename `HierarchicalMachine .to` since the current version does not work as intended and has also not been tested before. I guess I can assume it has not actually been used even though its mentioned in the ReadMe. 

This means the warning should be gone with the next release/with the next commit to master.

**Comment by lromor** [comment]
thank you @aleneum !
