### ISSUE TITLE
Question, Is that possible add callback to list-of-lists Transitions table

### ISSUE THREAD

**Issue by pwa16000** [pytransitions/transitions#282]
Hi,

I want to add callback functions to list-of-lists transitions table.

Original code like this:
==============
transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid', 'before': 'make_hissing_noises'},
    { 'trigger': 'evaporate', 'source': 'liquid', 'dest': 'gas', 'after': 'disappear' }
]

Was changed to:
===========
transitions = [
    ['melt', 'solid', 'liquid', 'make_hissing_noises'],
    ['evaporate', 'liquid', 'gas', 'disappear' ]
]

I found 'make_hissing_noises' works fine, but the state does not transfer to 'liquid'.

Is there anything wrong with the re-write transitions list-of-lists table? or current version transitions does not support list-of-lists transitions table with callback?

Best regards
Philip
 
All code I'm trying
===============
from transitions import Machine

class Matter(object):
    def make_hissing_noises(self): print("HISSSSSSSSSSSSSSSS")
    def disappear(self): print("where'd all the liquid go?")

states = ["solid", "liquid", "gas"]

transitions = [
    ['melt', 'solid', 'liquid', 'make_hissing_noises' ],
    ['evaporate', 'liquid', 'gas', 'disappear']
]

lump = Matter()
machine = Machine(lump, states, transitions=transitions, initial='solid')
lump.melt()
lump.evaporate()

------------------
output:
HISSSSSSSSSSSSSSSS
Traceback (most recent call last):
  File "C:\Users\lenovo\code\python\PythonMisc\trans-2.py", line 22, in <module>
    lump.evaporate()
  File "C:\Python27\lib\site-packages\transitions\core.py", line 382, in trigger
    return self.machine._process(func)
  File "C:\Python27\lib\site-packages\transitions\core.py", line 1007, in _process
    return trigger()
  File "C:\Python27\lib\site-packages\transitions\core.py", line 396, in _trigger
    raise MachineError(msg)
transitions.core.MachineError: "Can't trigger event evaporate from state solid!"

**Comment by aleneum** [comment]
Hello @pwa16000,

you can use a list of lists but I would highly discourage you from doing that since you need to keep track of the exact order of arguments passed to `add_transition`.

> Is there anything wrong with the re-write transitions list-of-lists table? 

The order is ` trigger, source, dest, conditions=None, unless=None, before=None, after=None, prepare=None, **kwargs` and list entries will be mapped in that order which means your 4th entry is actually mapped to `conditions`.  Conditions will be executed (thats why you see the hiss) but when the function does not return a 'truely' value, the transition will be halted.

For you code to work you need to pass `['melt', 'solid', 'liquid', None, None, 'make_hissing_noises'] which is not as comprehensible as the dictionary way.

**Comment by pwa16000** [comment]
Hello Aleneum,

Thanks very much for your information, it works well.

Best Regards
Philip
