### ISSUE TITLE
Not able to pickle GraphMachine

### ISSUE THREAD

**Issue by ansumanm** [pytransitions/transitions#292]
from transitions.extension import GraphMachine as Machine

m = Machine(..)

pickle.dump(m) gives error.

TypeError: can't pickle SwigPyObject objects

It works fine for Machine.

**Comment by aleneum** [comment]
Hello @ansumanm,

which Python version and which version of `transitions` are you using? I tested the code snippet below with Python 3.6 and it works fine.

```python
from transitions.extensions.diagrams import GraphMachine as Machine
import pickle


m = Machine(states=['A', 'B', 'C'])
pickle.dumps(m)
```

Note that the documentation mentions [here](https://github.com/pytransitions/transitions#re-storing-machine-instances) that Python 2.7 requires `dill`.

**Comment by ansumanm** [comment]
Thanks for your response.
There are other elements in the class, it works fine for Machine, only if I turn on GraphMachine, it breaks.

$python -V     
Python 3.6.3

>pip show transitions
Name: transitions
Version: 0.6.4
Summary: A lightweight, object-oriented Python state machine implementation.
Home-page: http://github.com/pytransitions/transitions
Author: Tal Yarkoni
Author-email: tyarkoni@gmail.com
License: MIT
Location: /home/ansuman/env3/lib/python3.6/site-packages
Requires: six

**Comment by aleneum** [comment]
Could you provide a minimal example where this error occurs? Right now, I can just guess whats going wrong. Did you override `__getstate__` and `__setstate__` or implement other pickle specific behaviour? When pickling `GraphMachine`, it is necessary to omit the `graph` property because the `pygraphviz.AGraph` object is not pickable. Usually this is taken care of by `GraphMachine.__getstate__`.

**Comment by ansumanm** [comment]
The following code gives error:-                                                                                                  
Exception ignored in: <bound method Test.__del__ of <__main__.Test object at 0x7ff64a23f7f0>>                            
Traceback (most recent call last):                          
  File "repro.py", line 41, in __del__                      
    pickle.dump(self,f)       
TypeError: can't pickle SwigPyObject objects  

Code:-
========
import pickle
from transitions.extensions import GraphMachine as Machine

class Test:
    states = ['A', 'B', 'C']

    t = 'trigger'
    d = 'dest'
    s = 'source'
    c = 'conditions'

    transitions = [
            {t: 'to_B', s: 'A', d: 'B', c: 'true_func'},
            {t: 'to_C', s: 'A', d: 'C', c: 'true_func'},
            {t: 'to_C', s: 'B', d: 'C', c: 'true_func'},
            ]

    def __init__(self):
        self.machine = Machine(model=self, states=self.states,\
                transitions=self.transitions,\
                title = 'Example', \
                send_event=True,\
                after_state_change='asc',\
                initial='A',\
                auto_transitions=False, ignore_invalid_triggers=True)

    def asc(self, event_data):
        pass

    def on_enter_B(self, event_data):
        print('Entering B')

    def on_enter_C(self, event_data):
        print('Entering C')

    def true_func(self, event_data):
        return True

    def __del__(self):
        with open('transition.pickle', 'wb') as f:
            pickle.dump(self,f)

def main():
    t = Test()

if __name__ == '__main__':
    main()

**Comment by aleneum** [comment]
Hello @ansumanm,

now I see the problem: The machine of your `Test` class will add the `AGraph` to the model (self) which makes the `Test` instance unpicklable. Currently, we work around this issue by not pickling the graph when it has been added to the machine itself. This is usually the case when the machine also acts as the model. For other cases (machine != model) there is not much `GraphMachine` can do about since it cannot (or should not) override models' pickling behaviour or tinker with attributes.

So, with the current state of transitions, you have at least 3 ways to deal with it: 

1. Delete `Test.graph` before the pickling attempt 
2. Copy `GraphMachine.__getstate__` and `GraphMachine.__setstate__` and add it to your Model (`Test`) to prevent `Test.graph` from being pickled
3. Let `Test` inherit from `GraphMachine` instead of membership

The first approach (1) is probably the most suitable solution for your use case. If you run pickle right before the object is deleted anyway, you can also go ahead and remove graph right away. 
Implement your own `setstate/getstate` (2) is probably the most flexible solution but also adds some code complexity. I mentioned (3) for completeness but I do prefer a clear distinction between model and machine like you do it currently. 

Example for (1):
```
import pickle
from transitions.extensions import GraphMachine as Machine


class Test:

    def __init__(self):
        self.machine = Machine(model=self)

    def __del__(self):
        with open('transition.pickle', 'wb') as f:
            del self.graph  # this has been added self.machine
            pickle.dump(self, f)

def main():
    t = Test()

if __name__ == '__main__':
    main()
```

That being said. We might reconsider adding the `AGraph` to the model objects. This is certainly an inconvenience for library users.

**Comment by aleneum** [comment]
Hmmkay.. unfortunately unpickling seems to have some issues. I will investigate that during the course of tomorrow.

**Comment by aleneum** [comment]
The unpickling issue seems to be related to some properties of `Machine.events` not being available in `__setstate__`. Interestingly, the observed errors varies depending on the used Python 3 version (tested 3.4.8, 3.5.5 and 3.6.4). I assume its the level of recursive references and partials that makes serialisation tough for `pickle` here. Because of the fact it works 'sometimes' with Python 3.4 and 3.5 I filed a [bug report](https://bugs.python.org/issue33249).

**Comment by ansumanm** [comment]
Thanks a ton for maintaining this wonderful library..

**Comment by aleneum** [comment]
A workaround is in progress but testing now fails because of unit test related pickling issues see [this issue](https://github.com/uqfoundation/dill/issues/262). This could also be worked around but solving this is the preferable solution.

**Comment by aleneum** [comment]
This should be solved now. [This](https://github.com/pytransitions/transitions/commit/4b38b9d90101541f36dbeafc89355c0298f1c493#diff-cc4345db19ff44863e9122c74e9f383fR488) test should make sure that it does work in the future. The current solution is to initialize the graph 'lazily' which means it wont be initialized in `__setstate__` but the first time it is actually used. The dill issue is not that relevant but I will track the development of the previous mentioned pickle issue just.

If this does not solve your issue feel free to comment and I will reopen the issue if there is more to do. transitions 0.6.5 will be released when travis builds get on their feet again. I assume PyPi faces issues due to their current warehouse launch.
