### ISSUE TITLE
Question about multiple destination [concurrency]

### ISSUE THREAD

**Issue by chace20** [pytransitions/transitions#297]
I know that multiple source is correct and defined as follow:
```
transition_1 =  {'trigger': 'jump', 'source': ['a','b'], 'dest': 'c'}
```
But when it comes to multiple destination, it's wrong.
```
transition_2 = {'trigger': 'jump', 'source': 'a', 'dest': ['b','c']}
```
I don't know how to implement using this library. Anyone can give me some ideas? or add this feature to this library? Welcome to discuss.

**Comment by aleneum** [comment]
Hi @chace20,

what should be the goal of transition_2. Should your model end up in 2 states at the same time?

**Comment by chace20** [comment]
Yeah, I think so. There are some parallel states.

**Comment by aleneum** [comment]
I see. Unfortunately transitions does not support concurrency (yet). Models are supposed to have ONE specific state. However, since transitions support multiple models it is possible to have models with different states in the same machine. One way to realize this is to let the model do the spawning of submodels as seen below:

```python
from transitions import Machine


class Model(object):

    def __init__(self):
        self.submodels = {}

    def on_enter_B(self, event_data):
        self.submodels['B'] = Model()
        event_data.machine.add_model(self.submodels['B'], initial='C')

    def on_exit_B(self, event_data):
        try:
            event_data.machine.remove_model(self.submodels['B'])
        except ValueError:
            pass
        finally:
            del self.submodels['B']

    def on_exit_C(self, event_data):
        event_data.machine.remove_model(self)

    @property
    def current_state(self):
        return [model.state for model in self.submodels.values()] + [self.state]


model = Model()
m = Machine(model, states=['A', 'B', 'C', 'done'], transitions=[['jump', 'A', 'B'], ['leave', 'B', 'A'], ['finish', 'C', 'done']],
            initial='A', send_event=True, ignore_invalid_triggers=True)
model.jump()
print model.current_state
m.dispatch('finish')
print model.current_state
model.leave()
print model.current_state
```

If you have any suggestions about how this process can be streamlined, let me know.

**Comment by aleneum** [comment]
Since the above mentioned 'workaround' does not satisfy proper concurrency, I add 'concurrent states' as a feature for 0.7.0. This requires some significant changes in the nested states extension but I assume this tradeoff should be worth it since there is a lack of (Python) state machine libraries that support concurrency.

**Comment by amitabhn** [comment]
Concurrent states would be super useful feature to add! Any updates on this?

**Comment by devoteam-dev1** [comment]
Hi @aleneum,
Do you have any status on concurrency?

**Comment by aleneum** [comment]
transition 0.8.0 now supports parallel states as mentioned and illustrated in #371.
Having parallel states is solved by using nested states with the `parallel` keyword.

Transitions with mutliple destinations are not supported though. I opted for the nested solution since this is how it is defined in state charts as far as I can tell and I could also not think of a custom `transitions`-way of definining scopes and how to determine when concurrent states should be exited again.
