### ISSUE TITLE
Attaching attributes to instances of class `Transition`.

### ISSUE THREAD

**Issue by prashast** [pytransitions/transitions#315]
Hi, I wanted to know if it is possible to add additional attributes to the these instances of 
the `Transition` class themselves? 
Perhaps is it possible for me to inherit this `Transition` class and add additional functionality to it?

The reason why I wanted this was because I wanted to maintain context on a per-transition basis and then trigger transitions from each state based on the local context of the available transitions.

**Comment by aleneum** [comment]
Hi @prashast,

> Perhaps is it possible for me to inherit this Transition class and add additional functionality to it?

this can be done quite easily by creating your own subclass of `Transition` and assign it to the `transition_cls` class attribute of your custom subclass of `Machine`:

```python
from transitions.core import Machine, Transition


class SubTransition(Transition):

    def __init__(self,  *args, **kwargs):
        self.new_arg = kwargs.pop('new_arg', None)
        super(SubTransition, self).__init__(*args, **kwargs)

    def execute(self, event_data):
        print("I got {0}".format('nothing' if self.new_arg is None else self.new_arg))
        return super(SubTransition, self).execute(event_data)


class SubMachine(Machine):
    transition_cls = SubTransition


transitions = [
    {'trigger': 'go', 'source': 'A', 'dest': 'B', 'new_arg': 'something'},
    ['go', 'B', 'A']
]

m = SubMachine(states=['A', 'B'], transitions=transitions, initial='A')
m.go()
m.go()
```

Just make sure you don't accidentally pass unknown attributes to the core classes. This is why custom arguments need to be popped from `kwargs`.

**Comment by prashast** [comment]
Hi @aleneum,

Thanks again for such a detailed reply. This is definitely what I was looking for. One additional thing, is there an exposed API to query the attributes attached with the subclass directly without executing the trigger callback function? 

The reason why I ask for this is because I want to based on the current state I am in, I want to query the attributes for the different legal transitions available and then trigger the appropriate transition. Conditional transitions won't help because they would only work based on the local context whereas I want to take into account multiple contexts based on the available transitions.

I could create a mapping of the created subclasses to the transitions when they are created but I was wondering if `Transitions` itself exposes a way for me query the attributes. 

Thanks  again for  being so responsive and creating such a clean FSM library! :)

**Comment by aleneum** [comment]
There is `Machine.get_triggers` which allows you to get valid events for a certain state.
By accessing `Machine.events` you get call transitions associated with this event. An event organises transitions by departure state which should be what you are looking for. If you search the issue tracker and SO you probably find enough information to get this working. If not, consider posting your issue at SO.  This has several advantages:

* Your question gains higher visibility since most developers look for help there
* The targeted community is larger; Some people will even help you to formulate a good question People get 'rewarded' with 'reputation' to help you.
* You also gain reputation in case this questions pops up more frequently. It's a win-win situation.

**Comment by prashast** [comment]
Sounds good, thanks again!
