### ISSUE TITLE
State extension change the workflow ?

### ISSUE THREAD

**Issue by potens1** [pytransitions/transitions#316]
It sounds like using the Error State extension (introduced in #231 ) changes the workflow, I guess using any of the states extensions (but Tag), will break the `enter` callback, and they are not compatible each other)

Maybe I'm missing something (in the doc ?), but a simple example show it :

```python
import logging

from transitions import Machine
from transitions.extensions.states import add_state_features, Error

logging.basicConfig(level=logging.DEBUG)


@add_state_features(Error)
class CustomMachine(Machine):
    pass

def print_enter():
    print("Enter B")

def print_before():
    print("Before B")

states = ["A",
          {"name": "B", "on_enter": print_enter}, "C"]
transitions = [
    {"trigger": "to_B", "source": "A", "dest": "B", "before": print_before},
    ["to_C", "B", "C"],
]

m = Machine(
    states=states, transitions=transitions, auto_transitions=False, initial="A"
)

m2 = CustomMachine(
    states=states, transitions=transitions, auto_transitions=False, initial="A"
)
# Working the usual way
m.to_B()
assert m.state == "B"
# Seems not working
m2.to_B()
assert m2.state == "B"
print("State now", m2.state)
```
The output of this is:
```DEBUG:transitions.core:Initiating transition from state A to state B...
Before B
DEBUG:transitions.core:Executed callback '<function print_before at 0x7f8f75e28378>' before transition.
DEBUG:transitions.core:Exiting state A. Processing callbacks...
INFO:transitions.core:Exited state A
DEBUG:transitions.core:Entering state B. Processing callbacks...
Enter B
INFO:transitions.core:Entered state B
DEBUG:transitions.core:Initiating transition from state A to state B...
Before B
DEBUG:transitions.core:Executed callback '<function print_before at 0x7f8f75e28378>' before transition.
DEBUG:transitions.core:Exiting state A. Processing callbacks...
INFO:transitions.core:Exited state A
State now B
```
the `print_enter` callback is never called.

**Comment by aleneum** [comment]
Hello @potens1,

you are right. `Error.enter` is not calling its super class equivalent. I see you have already fixed that in your PR. Thanks for that! You mention issues with `Timeout` as well? Could you provide an example which is still not working, even after fixing `Error`?

**Comment by potens1** [comment]
Hello @aleneum,
My bad, I was talking with Timeout AND Error at the same time, I was thinking the `enter` method of the state will either from `Timeout` or from `Error` (depends on MRO and order you put), but not both...

**Comment by aleneum** [comment]
Yeah, it *should* call both methods in an order which cannot be altered due to the MRO as you mentioned. Additionally, there might be issues when a `MachineError` is raised during the processing of a timeout event. The raised exception cannot be caught directly in the main thread as timeouts are processed in a separate thread.
Unfortunately, there is no nice way to implement timeouts (for Python 2 and 3) without using threads as far as I know.

**Comment by potens1** [comment]
About the threads thing, my point of view is `pytransitions` should not bother with IO at all, it should be a lib _à la_ [sans-io](https://sans-io.readthedocs.io/) (io and blocking code outside of the lib), this way, it is compatible with asyncio, threading, multiprocess _et al._, only events should be passed to and from the blocking part (i.e., in my case, I'm rewriting the Timeout extension to just push the timeout events to a queue, and another part of my soft is managing the queue, the nice thing is either on python2 with queue or python3 with asyncio.queue, both have a method put_nowait and get_nowait, then my soft could use threading.Timer, or sched.scheduler or loop.call_later/call_at, whatever). Still two years to wait before stopping bothering with this kind of things (py2/py3) (but some like django have already announced 2020 is now...)
About the MRO, I'm sorry, but I don't understand how it working, I mean, aren't we here in a diamond inheritance with
```dot dep.svg
digraph D {
  State -> {Timeout, Error} -> {CustomState}
}
```
So, I don't get how the Timeout.enter and Error.enter are called both (sorry for my ignorance)

**Comment by aleneum** [comment]
> I mean, aren't we here in a diamond inheritance ...

Yes. Since every new style Python class is derived from `object`, practically every multi-inheritance scenario results in a diamond. Afaik, Python uses [C3 linearization](https://en.wikipedia.org/wiki/C3_linearization) since Python 2.3 [[1]](https://www.python.org/download/releases/2.3/mro/) to deal with that.

> to just push the timeout events to a queue, and another part of my soft is managing the queue

Using queues/asyncio is definitely the way to go for sophisticated use cases. This requires some logic which cannot be provided by `transitions`. As discussed (e.g [here](https://github.com/pytransitions/transitions/issues/198)) `state.Timeout` should be considered a tradeoff.
