### ISSUE TITLE
Processing the Event in Transitions without a if/elif statement

### ISSUE THREAD

**Issue by SuperChomsky** [pytransitions/transitions#322]
I don't know if it's possible to do what i am asking for, if it is not, i think it could be a good feature to add in Transitions. I want to implement a FSM where the transition are triggered by an event that is processed by avoiding a if/elif statement.

For example: I have a simple FSM of a lamp, if it came (in a non-deterministic way) the 'goInlampOn' event we move to the 'on' state, if the 'goInlampOff' event arrives we move to the 'off' state.
So my question is:

is there a way to create a method called  'process_event(event)' in the FSM class that process each event with the logic of my FSM without using a very long ( not in this very simple case) if-elif statement ?
Here an example of the code:

```
class MyFsm(object):
    
    transitions = [
        {'trigger': 'switchOff','source':'on','dest':'off'},
        {'trigger': 'switchOn','source':'off','dest':'on'}
    ]    
    def __init__(self):
        ''' initialating the FSM '''      
        self.machine = Machine(model=self, states = self.states ,transitions= self.transitions, initial = 'on' )       
        on = On()
        off = Off()
        self.machine.add_state(off)
        self.machine.add_state(on)
   

            
    #A SMART SOLUTION TO IMPLEMENT THIS METHOD WITHOUT USING   if state == off: ... elif state==on...   
    def process_event(self,event):              
         
         if self.state == 'off':            
             if event == 'goInlampOn':
                 self.switchOn()
                
         elif self.state == 'on':          
             if event == 'goInlampOff':
                 self.switchOff()

```

**Comment by aleneum** [comment]
Hi @SuperChomsky,

thanks for following by recommendation and post your question and Stackoverflow ([link](https://stackoverflow.com/questions/53036689/transitions-in-an-event-driven-finite-state-machine)). Please avoid cross-posting (posting the same question multiple times in different places without references). I will close this issue since it does not contain a feature request or a bug report. Discussion/solutions should be posted in the linked [post](https://stackoverflow.com/questions/53036689/transitions-in-an-event-driven-finite-state-machine). Feel free to comment in case a feature request or bug report arises. I will reopen the issue if necessary.
