### ISSUE TITLE
Finite State Machine with the unknown transitions

### ISSUE THREAD

**Issue by leonbrag** [pytransitions/transitions#323]
Hi,
I have a following design, which I would like to use Transition for:

1. I have a set of source states (call it Ss)
2. I have a set of destination states (call it Sd)

Some transitions from Ss to Sd are valid. Some are not. However I don't really have any particulate event that triggers transition.

Is there a way to use Transition module for the case above?

Essentially I just want have something like this:

try:
   FSM.transition (source=SsN, destination, SdN, onsuccess="mySuccessFunc")
exception Exception as e:
   print ("this transition is not valid")

 I can create a dummy event, but then I will need to create a **separate** dummy event for **each** valid transitions. I can then iterate through all dummy events. This would accomplish a task, but it seems like  hack.

**Comment by aleneum** [comment]
Hello @leonbrag,

a transition requires an event name. This event however can be as generic as you like. You can register ALL transitions with the same event name.

```python
machine.add_transition(trigger='process', source=[<sources1>], dest='<dest1>')
...
machine.add_transition(trigger='process', source=[<sourcesN>], dest='<destN>')
```
This way you can call `model.process()` whenever a state change should happen/should be checked. They will be process in their addition order. Of course, invalid transitions (not being valid in the current state) will not be considered.

Additionally, this looks like a question about how to use transitions. Please refer to Stackoverflow for such matters. Posting there has several advantages:

Your question gains higher visibility since most developers look for help there
The targeted community is larger; Some people will even help you to formulate a good question
People get 'rewarded' with 'reputation' to help you. You also gain reputation in case this questions pops up more frequently. It's a win-win situation.

Currently, this issue neither contains a feature request nor a bug report. I will close it for now. Feel free to comment nevertheless. If a feature request or a bug report arises, I will reopen the issue again.
