### ISSUE TITLE
Method Chaining

### ISSUE THREAD

**Issue by prabhatM** [pytransitions/transitions#353]
Does it have method chaining or do we expect soon?

Prabhat

**Comment by aleneum** [comment]
Hello @prabhatM, 

> Does it have method chaining or do we expect soon?

I assume you talk about event chaining. Transition will not support method chaining because events are expected to return `True` or `False`. Introducing chaining would break basically every workflow we currently recommend. However, method chaining can be introduced easily by altering what events will return:


```python
from transitions import Machine, Event


def always_fails():
    return False


states = ['A', 'B', 'C']
transitions = [dict(trigger='fails', source='*', dest='A', conditions=always_fails)]


m = Machine(states=states, transitions=transitions, ordered_transitions=True, initial='A')
assert m.state == 'A'
assert m.next_state() is True
assert m.fails() is False
assert m.state == 'B'

# our custom event will return the model in question instead of the transition result
class ChainableEvent(Event):

    def trigger(self, model, *args, **kwargs):
        res = super(ChainableEvent, self).trigger(model, *args, **kwargs)
        # do something with the transition result 'res' here
        return model

# if you feel brave you can skip that step and 'monkey patch' Machine.event_cls = ChainableEvent instead
class ChainableMachine(Machine):
    event_cls = ChainableEvent

class Model:
    pass


m = ChainableMachine(states=states, transitions=transitions, ordered_transitions=True, initial='A')
assert m.next_state().fails().next_state().state == 'C'

# also works with dedicated model
model = Model()
m = ChainableMachine(model=model, states=states, transitions=transitions, ordered_transitions=True, initial='A')
assert model.next_state().fails().next_state().state == 'C'
```

**Comment by prabhatM** [comment]
I was thinking of a small application for kids where a box has yellow
colour. Then the user clicks or connects a magenta colour box so that the
resultant color becomes RED. Then connects a BLUE box and the resultant
color becomes PURPLE. Kind of Procedural color addition.

We can also think of a Number game with Addition, Substraction, Division
etc

**Comment by aleneum** [comment]
Dear @prabhatM,

your problem description is unfortunately a bit generic/vague.
If you require assistance concerning a bug report or feature request, it is necessary to be as precise as possible about the issue is you are facing. Additionally, questions should explicitly focus on transitions or the conceptual application of state machines. If you have a transitions-related issues I am happy to help.

**Comment by prabhatM** [comment]
Thank you for the clarification. I will explore Transitions further and
seek your help if I face any issues.

Regards

Prabhat
