### ISSUE TITLE
[Feature request] Support for source/destination information in machine callback

### ISSUE THREAD

**Issue by Matheus-Garbelini** [pytransitions/transitions#358]
Hello, is it possible to pass the source/destination transition before_state_change or after_state_change callback? I'm trying to log the transition, so if I receive this information in such callbacks I'd be able to do something like this: `print(state + '-->' + destination)`.

Thanks

**Comment by aleneum** [comment]
Hello @Matheus-Garbelini,

this can be done by passing `send_event=True` to `Machine`:

```python
from transitions import Machine

class Model:

    def after_state_change(self, event):
        print(event.transition.source, '->', event.transition.dest)

model = Model()
machine = Machine(model, states=['A', 'B'], send_event=True, initial='A',
                  after_state_change='after_state_change')
model.to_B()  # >>> A -> B
```

For future questions about 'How to do X with `transitions`', post on Stack Overflow first, making sure to tag your question with the transitions and python tags. Posting there has several advantages:

Your question gains higher visibility since most developers look for help there
The targeted community is larger; Some people will even help you to formulate a good question
People get 'rewarded' with 'reputation' to help you. You also gain reputation in case this questions pops up more frequently. It's a win-win situation.

I will close this issue for now since it does not contain a bug report or a feature request. Feel free to continue commenting. If a bug report/feature request arises, I will reopen the issue.

Best,
Alex

**Comment by Matheus-Garbelini** [comment]
Thanks @aleneum , sorry for the redundant issue. I missed this featured so I actually created a custom transition class just for that. Thanks for the response :+1:

**Comment by hollowgalaxy** [comment]
Note to @aleneum, using the `transitions` tag turns it into `transition` tag automatically when doing a search on StackOverflow, making it difficult to find questions related to this repo.

**Comment by aleneum** [comment]
@hollowgalaxy,

> ... tag automatically when doing a search on StackOverflow, making it difficult to find questions related to this repo.

you are right. I assume nowadays its less ambiguous to use the `pytransitions` tag instead ([ref](https://stackoverflow.com/questions/tagged/pytransitions)). I will update the README accordingly.
