### ISSUE TITLE
Take a logger parameter to override internal logger

### ISSUE THREAD

**Issue by dan-bar-dov** [pytransitions/transitions#359]
I'd like to incorporate the transitions log in my application log. 
If a machine could take a logger as an optional parameter, it would override the core _LOGGER.

**Comment by aleneum** [comment]
Hello @dan-bar-dov,

could you specify why retrieving the logger instance with `logging.getLogger('transitions')` is not sufficient for your use case?

**Comment by dan-bar-dov** [comment]
Perhaps it is because the logger confuses me, but I'd like the transitions log output to be formatted the same like the rest of my app logs. 
Currently I do use the` logging.getLogger('transitions')` but the log messages are formatted differently from my app, they also don't propagate to all my logging handlers.

**Comment by aleneum** [comment]
I suggest to have a deeper dive into logging. The logging objects in `transitions` will usually use the format, handles and log level specified in `basicConfig`.

Example
```python
from transitions import Machine

import logging

FORMAT_DETAIL = '%(asctime)-15s %(funcName)-8s %(name)s:%(lineno)d %(message)s'
FORMAT_SIMPLE = '%(levelname)s:%(message)s'

# https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles
logging.basicConfig(format=FORMAT_DETAIL, level=logging.DEBUG)

m = Machine(states=['A', 'B'], ordered_transitions=True, initial='A')
m.next_state()

logging.info("Simple formatted messages starting here ...")
logging.getLogger().handlers[0].setFormatter(logging.Formatter(FORMAT_SIMPLE))
logging.info("No everything is less detailed!")
m.next_state()
```

Output
```plain
2019-08-14 09:17:19,001 execute  transitions.core:242 Initiating transition from state A to state B...
2019-08-14 09:17:19,001 exit     transitions.core:121 Exiting state A. Processing callbacks...
2019-08-14 09:17:19,001 exit     transitions.core:124 Exited state A
2019-08-14 09:17:19,001 enter    transitions.core:114 Entering state B. Processing callbacks...
2019-08-14 09:17:19,001 enter    transitions.core:117 Entered state B
2019-08-14 09:17:19,002 <module> root:14 Simple formatted messages starting here ...
INFO:No everything is less detailed!
DEBUG:Initiating transition from state B to state A...
DEBUG:Exiting state B. Processing callbacks...
INFO:Exited state B
DEBUG:Entering state A. Processing callbacks...
INFO:Entered state A
```

More complex settings may require more configuration effort though. Currently, I don't see much benefit in adding another parameter. Especially because Python's logging system contains all the necessary tools to deal with this, imho.

Your issue might be more suitable for Stack Overflow. When you post on SO make sure to tag your question with the transitions and python tags. Posting there has several advantages:

Your question gains higher visibility since most developers look for help there
The targeted community is larger; Some people will even help you to formulate a good question
People get 'rewarded' with 'reputation' to help you. You also gain reputation in case this questions pops up more frequently. It's a win-win situation.

I will close this issue for now but feel free to comment if you have new insights or more to discuss. If a feature request or bug report arises I will reopen the issue.

**Comment by dan-bar-dov** [comment]
Thank you for taking the time to give a thorough answer. 
I will definitely follow your advise
Dan
