### ISSUE TITLE
"OR" conditions

### ISSUE THREAD

**Issue by sergei3000** [pytransitions/transitions#381]
As per the documentation, all the conditions should return `True` for a transition to execute.

It would be great to have disjunctive conditions too. Something like this:
`machine.add_transition('heat', 'solid', 'liquid', conditions=['is_really_hot'], or_conditions=['is_very_dense'])`
`machine.add_transition('heat', 'solid', 'gas', unless=['is_flammable', 'is_really_hot'], or_unless=['is_ice_cold', 'is_moving'])`
With possibility of multiple `or...`'s per each transition.

**Comment by aleneum** [comment]
Hi @sergei3000,

this has been discussed in #288 and #336. Right now there is no integrated way for OR statements. I proposed a workaround/extension for this as seen in [here](https://github.com/pytransitions/transitions/issues/288#issuecomment-364896632). Let me know what you think about it and if this is helpful.

**Comment by sergei3000** [comment]
Hi @aleneum,
Sorry for duplicating, I didn't notice those two issues.

As for your workaround/extension, it seems a great idea to have something like this integrated into `core`, but the `unless` part looks as `xor` rather than `or` to me because of this part: "`'unless': ['A', ['B', 'C']]` becomes `not A and not (B and C) = not A and (not B or not C)`".

I actually meant inclusive `or` in this issue, but perhaps `xor` would be nice to have too.

**Comment by aleneum** [comment]
Hi @sergei3000,

> but the unless part looks as xor

for the two variable case it acts close to `xor` but not completely since `not A or not B` is true for `A=False` and `B=False` but `xor` is not. The operation to conduct depends on `op` in `ConditionList.check`:

```python
class ConditionList(transitions.core.Condition):

    def __init__(self, func, target=True):
        super(ConditionList, self).__init__(func, target)
        self.func = transitions.core.listify(self.func)

    def check(self, event_data):
        op = any if self.target else all  # <-- sets the used operation
        predicates = [getattr(event_data.model, f) if isinstance(f, string_types) else f for f in self.func]
        if event_data.machine.send_event:
            return op(p(event_data) for p in predicates) == self.target
        return op(p(*event_data.args, **event_data.kwargs) for p in predicates) == self.target
```

You could set `op` to be `any` for both cases, conditions (`self.target=True`) and unless (`self.target=False`) to achieve 'global' `or`. Currently, inclusive `or` for `conditions` can also be achieved by defining multiple transitions:

```python
machine.add_transition('heat', 'solid', 'liquid', conditions=['is_really_hot'])
machine.add_transition('heat', 'solid', 'liquid', conditions=['is_very_dense'])
```
This does not work for `unless` though however. `unless` acts as an `or` already since its basically negated `conditions`:

```
unless: A, B -> not A and not B -> not (A or B)
```
You might see that finding the 'silver bullet' that fits all requirements considering condition concatenation is quite tough. Some solutions might work for mutual exclusions but do not cover other use cases such as inclusive `or` for both `conditions` and `unless`.

Unfortunately, I haven't seen a flexible yet easy to comprehend way to deal with this complexity.
This is why I currently think that this functionality is something that needs to be added depending on the use case to be tackled. For instance, you can pass lambdas and functions to conditions and unless to deal with this. Based on your example above this could look like this:

```python
from transitions.core import Machine

class Model:

    def is_flamable(self, props):
        return 'flamable' in props

    def is_hot(self, props):
        return 'hot' in props

    def is_cold(self, props):
        return 'cold' in props

    def is_moving(self, props):
        return 'moving' in props


m = Model()
machine = Machine(model=m, states=['A', 'B'], initial='A')
machine.add_transition('go', 'A', 'B', conditions=lambda props: m.is_flamable(props) or
                                                                m.is_hot(props))
machine.add_transition('go', 'B', 'A',
                       # (not A and not B) or (not C and not D)
                       # -> not(A or B) or not(C or D)
                       # -> not ((A or B) and (C or D)) -> unless: (A or B) and (B or C)
                       unless=lambda props: (m.is_flamable(props) or m.is_hot(props)) and
                                            (m.is_cold(props) or m.is_moving(props)))
m.go(props=['flamable'])
assert m.state == 'B'
m.go(props=['moving', 'hot'])
assert m.state == 'B'
m.go(props=['cold'])
assert m.state == 'A'
```

**Comment by sergei3000** [comment]
> it acts close to xor but not completely since not A or not B is true for A=False and B=False but xor is not

Yeah, I had totally misinterpreted your words from #288. Sorry about that.

Thank you so much for all these tips. They are very helpful.

**Comment by aleneum** [comment]
Closing this since there is no easy way to provide flexible enough 'or' handling. There are however ways to adapt `Conditions` to a variety of needs. I will close this for now. Feel free to comment if there is more to add to the topic. I will reopen the isse when necessary.
