### ISSUE TITLE
Add a Hierarchical variant to AsyncMachine 

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#399]
Currently this implementation is missing from the library.

Unless there's an implementation limitation I'm unaware of I assume that nobody requested it until now and that's why it isn't implemented.

**Comment by thedrow** [comment]
@aleneum Apologies for the direct ping. I'm willing to implement this but I just need some directions.

**Comment by aleneum** [comment]
Hi @thedrow,

this requires some refactoring in the `HierarchicalMachine` (I am working on it) since I like to keep the codebase to be maintained as small as possible. Unfortunately, async code has the tendency to "creep" ([ref](https://hackernoon.com/controlling-python-async-creep-ec0a0f4b79ba)) and causes a lot of code to be written more or less twice when you want to maintain a (Python 2-compatible) synchronous variant and another one using async. I cannot really tell you what needs to be done because I have to test myself what works and what does not. I hope to push an experimental version until the beginning of next week.

**Comment by thedrow** [comment]
@aleneum Can this be closed?

**Comment by aleneum** [comment]
`HierarchicalAsyncMachine` has been implemented and added to `MachineFactory`. It has not been explicitely documented so far. Furthermore, it should be considered experimental until the refactored version of `HierarchicalMachine` is completely stable.
