### ISSUE TITLE
0.8 bug: nested state cannot be initial state

### ISSUE THREAD

**Issue by caha321** [pytransitions/transitions#402]
minimal example (slightly modified example of the documentation):

```
from transitions.extensions import HierarchicalMachine as Machine

states = ['A', 'B',
  {'name': 'C', 'children':['1', '2',
    {'name': '3', 'children': ['a', 'b', 'c']}
  ]}
]

transitions = [
    ['reset', 'C', 'A']
]

# we rely on auto transitions
machine = Machine(states=states, transitions=transitions, initial='C_1')
```

Result:

> ValueError: State 1 cannot be added since it already exists.

In version 0.7.2 this worked perfectly fine

**Comment by aleneum** [comment]
Hi @caha321,

first:

> ValueError: State 1 cannot be added since it already exists.

this error is for sure misleading and will be adressed

second:

this change in behaviour has been intentional to hold the increased complexity after adding parallel states at bay. The ReadMe mentions (a bit too vaguely I guess)

> "Which substate to enter is defined by initial which should always point to a direct substate."

I expected that the use case like the one you mentioned can easily be altered to

```python
from transitions.extensions import HierarchicalMachine as Machine

states = ['A', 'B',
  {'name': 'C',
   'children': ['1', '2', {'name': '3', 'children': ['a', 'b', 'c']}],
   'initial': '1'}
]

transitions = [
    ['reset', 'C', 'A']
]

# we rely on auto transitions
machine = Machine(states=states, transitions=transitions, initial='C')
assert machine.is_C_1()
```

However, I am willing to re-evaluate this design decision if there are use cases that cannot be adjusted to the above mentioned approach. Feedback is definitely welcome. I know that changes like this are inconvenient and I only opted for it since parallel state support increases the versatility of `transitions` significantly. You can upgrade to 0.8.0 and use the old HSM implementation until we find a solution though:

```python
from transitions.extensions.nesting_legacy import HierarchicalMachine as Machine

states = ['A', 'B',
  {'name': 'C', 'children':['1', '2',
    {'name': '3', 'children': ['a', 'b', 'c']}
  ]}
]

transitions = [
    ['reset', 'C', 'A']
]

# we rely on auto transitions
machine = Machine(states=states, transitions=transitions, initial='C_1')
assert machine.is_C_1()
```

Unfortunately, `nesting_legacy.HierarchicalMachine` cannot be used in conjunction with `GraphMachine` support.

**Comment by caha321** [comment]
Hi @aleneum 

thanks for the quick answer and explanation. Your suggested solution is actually what I was doing anyway in addition to wrong initial='C_1' parameter. The exception message just threw me off and I expected bigger issues ;)

**Comment by aleneum** [comment]
>  ... in addition to wrong initial='C_1'

it's perfectly reasonable to expect this to work it might be supported in the future (again) depending on how crucial this feature has been to the community. Thanks again for the report!
