### ISSUE TITLE
Comparison with django-fsm

### ISSUE THREAD

**Issue by somghosh** [pytransitions/transitions#435]
I wanted to know the pros and cons of `django-fsm` vs  `transitions` , https://github.com/viewflow/django-fsm

Any info on the relative plus/minus of the two packages and which one is suitable where, if any such use cases favour one over another inside the business logic/transitions use cases will be appreciated

**Comment by aleneum** [comment]
Hello @somghosh,

since I don't know `django-fsm`, I cannot really compare it to `transitions`. `django-fsm` looks maintained and probably integrates easier with django as it is specifically designed for that. But I don't know if it has features `transitions` has not or vice versa.

I know that some people successfully use `transitions` with django but since it is not specifically designed for that purpose, some things need to be taken into account: `transitions` will decorate every model instance with convenience functions. This might cause a significant overhead. But there are solutions for that. See the [FAQ notebook](https://github.com/pytransitions/transitions/blob/master/examples/Frequently%20asked%20questions.ipynb) in examples and have a look at these issue:  #434, #146. Someone wrote a django wrapper for `transitions` which you can find [here](https://github.com/PrimarySite/django-transitions). It has not been updated in a while so I cannot tell you how well it works with recent versions of transitions. Furthermore, you could search the Github issue tracker with `django` as a keyword and you find mutliple questions and stories about `django` and `transitions`.

**Comment by aleneum** [comment]
This became unfortunately stale. I will close it for now. Maybe a plattform like Reddit ([r/python](https://www.reddit.com/r/Python/)) or [Hacker News](https://news.ycombinator.com) will result in a more lively discussion. Feel free to open feature requests if you have gathered some feedback.
