### ISSUE TITLE
Orthogonal edge routing with Graphviz

### ISSUE THREAD

**Issue by rSrkn** [pytransitions/transitions#441]
Hello, 
How can I configure state machine to draw graph with straight line connections ( "orthogonal edge routing") instead of curved lines. That feature exists in Graphviz as explained in the below question:
https://stackoverflow.com/questions/8939973/how-can-i-generate-rectangle-style-edges-instead-of-curves-in-graphviz

but I could not find how to apply this to the state machine.
Does anybody have any idea or can forward me to any useful information?

**Comment by aleneum** [comment]
Hello @rSrkn,

as illustrated in the [Custom Styling](https://github.com/pytransitions/transitions/blob/master/examples/Graph%20MIxin%20Demo.ipynb) of the graph example notebook, you can edit graph, node, edge and subgraph attributes. Since `splines` is a graph attribute, it should be added to the `GraphMachine.machine_attributes` attributes. For illustration purposes I also altered the flow direction. When using orthogonal edges you have set `xlabel` instead of `label` for edges. The `pygraphviz` backend allows to iterate over all edges and fix that quite easily. In case you use the `graphviz` backend, some more sophisticated replacement strategy might be required. However, in both cases you can retrieve the graph with `Model.get_graph` and edit as you like before you draw it.

```python
from transitions.extensions.diagrams import GraphMachine

states = ['A', 'B', 'C', 'D']
transitions = [['go', 'A', 'B'], ['process', 'A', 'C'], ['go', 'C', 'D']]

m = GraphMachine(states=states, transitions=transitions, initial='A')

m.get_graph().draw('default.png', prog='dot')

GraphMachine.machine_attributes['rankdir'] = 'TB'
GraphMachine.machine_attributes['splines'] = 'ortho'

graph = m.get_graph(force_new=True)
for e in graph.iteredges():
    e.attr['xlabel'] = e.attr['label']
    del e.attr['label']
graph.draw('ortho.png', prog='dot')

```

### default.png

![default](https://user-images.githubusercontent.com/205986/84486358-9b166300-ac9d-11ea-9907-0117872a94cd.png)

### ortho.png

![ortho](https://user-images.githubusercontent.com/205986/84486399-a79abb80-ac9d-11ea-9af8-dc8c26748a0b.png)

**Comment by rSrkn** [comment]
Thank you @aleneum,

As you mention 'splines' and 'xlabel' solved the issue for me.
