### ISSUE TITLE
Possibility to alter the node posiition?

### ISSUE THREAD

**Issue by dennylab** [pytransitions/transitions#450]
Hi,

My graph looks like this:
![smb0](https://user-images.githubusercontent.com/28300445/87635861-09888e00-c740-11ea-8edd-980091be8d54.png)

Is it possible to move the "new" node to the top as example?
I tried for node in graph.iternodes(): node.attr["pos"] = "0,0!", but it didn't work...

Thanks

**Comment by aleneum** [comment]
Hello @dennylab,

the diagram module generates a graph which is either more or less plain 'dot' (backend: `graphviz`) or a more sophisticated `AGraph` (backend: `pygraphviz`). If you want to spice up the layouting I'd suggest asking the 'Graphviz' community directly (via Stackoverflow for instance) since this is not specifically related to `transitions`. `pygraphviz` provides multiple output stages (pre- and post-layouting maybe?) but again, this is not the right issue tracker. I will close this issue. Feel free to comment if you consider this a matter of `transitions` and I will reopen the issue if a feature request or bug report arises.
