### ISSUE TITLE
Tests fail on python3.6

### ISSUE THREAD

**Issue by ConiKost** [pytransitions/transitions#454]
When I do run the tests, I can see them failing on python3.6. On newer python3.7 and onwards, all tests pass.

Log: https://pastebin.com/He0LwbPa

**Comment by aleneum** [comment]
Hi @ConiKost, 

the problem lies within `python setup.py test` which does not pick up `pytest` as a test suite. Thus, `conftest.py` isn't considered. Transitions `asyncio` support relies on the contextvars module which was introduced in Python 3.7. 
Even though  `python setup.py test` is considered deprecated (as your output also suggests), I added an alias to `setup.cfg` which should make sure `pytest` is used when the command is run.

**Comment by ConiKost** [comment]
> Transitions asyncio support relies on the contextvars module which was introduced in Python 3.7.

Does that mean, that python3.6 isn't supported anyway and python3.7 and newer should be used?
I am asking, since I am the package maintainer of that package in Gentoo Linux.

**Comment by aleneum** [comment]
> I am the package maintainer of that package in Gentoo Linux.

First, thanks! Second, Gentoo ftw 🚀! Gentoo really helped me to get a better understanding of Linux in general. Spent way to much time just staring at mesmerizing emerge outputs.

> Does that mean, that python3.6 isn't supported anyway 

transitions supports Python 2.7 and all versions of Python 3. Users of `transitions` with versions before 3.7 can use the library but will not be able to use the `asyncio` extension module. Trying to import it will cause import errors due to the `contextvars` module. Everything else (nested states, diagrams, custom states, etc.) should work as expected.

**Comment by ConiKost** [comment]
You change doesn't seem to work. At least it fails for me to run the tests at all.

```
python3.6 setup.py test
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'pytest'
```

But never mind, I do now understand.
Instead calling "python test", I call directly pytest and all test, including python3.6, just work fine.

**Comment by aleneum** [comment]
> Your change doesn't seem to work. At least it fails for me to run the tests at all.

I see. Putting `pytest-runner`  in `requirments_test.txt` isn't enough which makes sense since `python setup.py test` does not use `requirements_*.txt` files. I tried putting `pytest-runner` in `tests_require` but seems like it has to be `setup_require`. Anyway, it seems like `pytest-runner` isn't recommended anyway. I will remove `pytest-runner` again since it does not really fulfill a purpose.

> Instead calling "setup.py test", I call directly pytest and all test, including python3.6, just work fine.

nice! good to hear. If there is a Gentoo guideline how Python requirements should be installed and how tests should be invoked give me a shout and I will check how to comply to it. From what I read `pip install -r ... ` and `pytest` / `tox` seems to be recommended these days.

**Comment by ConiKost** [comment]
> If there is a Gentoo guideline how Python requirements should be installed and how tests should be invoked give me a shout and I will check how to comply to it. 

Nope, everything is fine! Since Gentoo has some elegent way to running pytest, everything is good :-)
