### ISSUE TITLE
Avoiding custom triggers from showing in the graphs.

### ISSUE THREAD

**Issue by nithingowdakn** [pytransitions/transitions#464]
I am using the GraphMachine to model FSM and am using the wildcard symbol '*' for the trigger. The graph that prints will be having all the triggers written on it which actually fills-up the whole image. Is there any methods where-in I can avoid specific triggers from being displayed on the graph?
So, that it looks clean and still gets the job done?

Thanks in Advance

**Comment by aleneum** [comment]
Hello @nithingowdakn,

the diagram module generates a graph which is either more or less plain 'dot' (backend: graphviz) or a more sophisticated AGraph (backend: pygraphviz). If you want to spice up the layouting I'd suggest asking the 'Graphviz' community directly (via Stackoverflow for instance) since this is not specifically related to transitions. If you tag your SO question with [python] and [transitions] I will get a notice.  Pygraphviz provides multiple output stages (pre- and post-layouting maybe?) but again, this is not the right issue tracker. I will close this issue. Feel free to comment if you consider this a matter of transitions and I will reopen the issue if a feature request or bug report arises.
