### ISSUE TITLE
Async machine names and visibility

### ISSUE THREAD

**Issue by termim** [pytransitions/transitions#468]
1. The names for `asyncio` machines in `README.md` are different from what is in the code.
2. The `README.md` states that all extension classes could be directly imported from `transitions.extensions` but this does not work for `async` classes.

**Comment by aleneum** [comment]
Hi @termim,

thanks for pointing that out and also fixing it. The variants of `AsyncMachine` havent been exported to keep them isolated and cause the least possible inconvenience for Python 2 users (accidently importing the `asyncio` extention would cause a syntax error). But since most people probably did shift to Python 3 already, we can shift our focus more to Python 3 as well. Thank you for you PR. I am closing this since I consider this resolved. Feel free to comment if there is more to do and I will reopen the issue if necessary.
