### ISSUE TITLE
examples.ipynb in repo cant generate basic state diagrams

### ISSUE THREAD

**Issue by bbartling** [pytransitions/transitions#556]
Hi, 

When I try to run the example IPython notebook `Graph Mixin Demo Nested.ipynb` or any of the examples:
`AttributeError: module 'graphviz.backend' has no attribute 'ENCODING'`

- [ ] This is the same issue I have noticed on a recent Stack Overflow [here](https://stackoverflow.com/questions/69989691/how-to-resolve-attributeerror-module-graphviz-backend-has-no-attribute-encod) about issues trying to render in Pandas & scikit-learn that may use something similar, would anyone have any advice?

I've tried the [steps in the repo](https://github.com/pytransitions/transitions#:~:text=transitions%20can%20generate%20basic%20state%20diagrams%20displaying%20all%20valid%20transitions%20between%20states.%20) to generate basic state diagrams: 
```
conda install graphviz python-graphviz
pip install graphviz pygraphviz
```
 but no luck, anaconda.org has some [similar documentation ](https://anaconda.org/conda-forge/python-graphviz)to try:

> To install this package with conda run one of the following:
> conda install -c conda-forge python-graphviz
> conda install -c conda-forge/label/broken python-graphviz
> conda install -c conda-forge/label/cf201901 python-graphviz
> conda install -c conda-forge/label/cf202003 python-graphviz

Where still no luck trying on both Windows and Ubuntu 20.04 with Jupyter Labs, both same issue. I also notice that the [pygraphviz ](https://pygraphviz.github.io/documentation/stable/pygraphviz.pdf)has some documentation PDF where they mention an executable installer for Windows before using pip.

Everything seems to install OK but no matter what I try when I run the examples IPython notebook files in the repo locally I cant render anything.

Do I have to use IPython? Would there be anything simpler by chance for example to just save a .PNG file to a directory for a basic state diagram?

Thanks for any tips.

**Comment by aleneum** [comment]
Unfortunately, I cannot reproduce this issue. I guess it it related to some version clash between `graphviz` and `pygraphviz`. I tested `pygraphviz` 1.7 without any issues. You can check the [binder notebook](https://mybinder.org/v2/gh/pytransitions/transitions/master?filepath=examples%2FPlayground.ipynb) which should work fine. I cannot do much about `pygraphviz` issues though. But you can try to use the [graphviz](https://pypi.org/project/graphviz/) backend. You need to have this package installed **and** a working Graphviz environment with `dot` in you path, so that the `graphviz` package can find it. Conda installs this version with `conda install python-graphviz` and also takes care of Graphviz as far as I remember.

To use the `graphviz` backend instead of the `pygraphviz` backend in the notebooks, you just need to add `use_pygraphviz=False` to the `extra_args`:

```python
extra_args = dict(auto_transitions=False, initial='standing', title='Mood Matrix',
                  show_conditions=True, show_state_attributes=True, use_pygraphviz=False)
```

maybe this helps.

**Comment by bbartling** [comment]
I think its working now after I got pygraphviz properly installed referencing referencing the directions from the[ pygraphviz git repo](https://github.com/pygraphviz/pygraphviz/blob/main/INSTALL.txt#:~:text=pygraphviz-,Chocolatey,..%20code-block%3A%3A%20console,-PS%20C%3A%5C%3E%20choco) for Windows OS.

> Chocolatey

`PS C:\> choco install graphviz`

And in a cell within a Jupyter lab .ipynb running:
`pip install --global-option=build_ext --global-option="-IC:\Program Files\Graphviz\include" --global-option="-LC:\Program Files\Graphviz\lib" pygraphviz`

And presto, I can render the example.ipynb in this repo **: )**
