### ISSUE TITLE
mypy support?

### ISSUE THREAD

**Issue by Henddher** [pytransitions/transitions#574]
Hi, great library!!!!

Any plans to add support for mypy?

I'm using the library but missing types trigger [this error](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker)

```
error: Skipping analyzing "transitions": module is installed, but missing library stubs or py.typed marker  [import]
```

**Comment by jellyfish-tech** [comment]
Same for us, really looking forward to mypy support

**Comment by jellyfish-tech** [comment]
Same for us, but with `asyncio` extension. Really looking forward to mypy support

**Comment by aleneum** [comment]
`transitions` 0.9.0 has been published to PyPI and include typing stub files. Since `transitions` allows rather arbitrary argument types in functions and constructors there might be some false positive typing warnings. I personally would expect false negatives though. My goal for 0.9.0 was to satisfy `mypy` in 'common' usage scenarios without extensive typing of state and transition definitions.  Since nested configurations are often not accurately typed by `mypy` I opted for rather generic fallback types. Depending on your IDE this might lead to a vast amount of suggested type options. I am looking forward to community feedback to adjust this in upcoming releases. 

For now I hope this makes your work slightly easier.

**Comment by Henddher** [comment]
Thank you @aleneum 

Will have to update to 0.9.0 and see how it plays out.

**Comment by vaidik** [comment]
I am using 0.9.0 but cant seem to have type definitions work for trigger methods that are generated at run time

**Comment by aleneum** [comment]
Hello @vaidik,

>  cant seem to have type definitions work for trigger methods that are generated at run time

as far as I know this cannot be done with a static code analysis and type annotation. [docstrings](https://github.com/pytransitions/transitions/issues/383) might be useful. Alternatively, you could define your trigger methods on your model in advance for IDEs and code checkers to pick up and use [OverrideMachine](https://github.com/pytransitions/transitions/issues/588#issuecomment-1249408940) to allow `transitions` to override these methods during runtime. If you have a more elegant solution to deal with type checking and dynamic methods/attributes let me know.
